### ISSUE TITLE
Add operator recognition in latex support

### ISSUE THREAD

**Issue by PumpkinDemo** [runtimeverification/k-editor-support#32]
The latex support uses listings package and specifies configuration tags as comments to get highlighting on tags.

```latex
\lstdefinelanguage{K}{
  ...
  morecomment=[s][\color{ksyntaxgreen}]{<}{>}, % NOT a comment, easy way to parse k cells
  ...
}
```

This works fine but the case that the configuration cell contains `<`, especially when using the map updating operation.

The map updating operator `<-` will be recognized as the begin of comments (tags).

<img width="365" alt="截屏2023-01-24 20 04 48" src="https://user-images.githubusercontent.com/49865515/214287148-c07d41fd-9ab4-4dbd-b520-2318c5fad3b6.png">

There is a simple sulotion that defines the map updating operator as an operator keyword, using `otherkeywords` option of `\lstdefinelanguage` command, since the `keywords` option only supports tokens that start with a letter and go with letters and digits.

```latex
\lstdefinelanguage{K}{
  ...
  otherkeywords={<-, =>},
  keywords=[4]{<-, =>},
  keywordstyle=[4]\color{ksyntaxblack}\bfseries,
  morecomment=[s][\color{ksyntaxgreen}]{<}{>},
  ...
}
```

<img width="362" alt="截屏2023-01-24 20 10 27" src="https://user-images.githubusercontent.com/49865515/214288318-fee84906-efbc-4359-957c-4973dd333d5e.png">

**Comment by PumpkinDemo** [comment]
This doesn't address the problem but can mitigate the mis-highlighting to some extent.

Hope for a fundamental solution.

**Comment by radumereuta** [comment]
If you make a PR I will be more than happy to merge the changes.

**Comment by radumereuta** [comment]
Unfortunately, the fundamental solution means doing complete parsing, which can be difficult in K since we're using concrete syntax.
This solution seems more than satisfactory in this case.
