### ISSUE TITLE
Publish the k-vscode extension on Open VSX

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k-editor-support#35]
This is the open version of the Microsoft Extension Marketplace
https://open-vsx.org/

By default, Arch packages `code`, an open-source alternative to VSCode, that doesn't have access to MEM for possible [legal reasons](https://bugs.archlinux.org/task/67780). The alternative is above.

Thank you @geo2a for the suggestion.

**Comment by geo2a** [comment]
Here's the issue that provides context on why this is the case: https://github.com/microsoft/vscode/issues/31168

**Comment by radumereuta** [comment]
Done:https://open-vsx.org/extension/RuntimeVerification/k-vscode
and automated by: https://github.com/runtimeverification/k-editor-support/pull/44
